
#Docker Compose File
# YAML file that defines how Docker containers should behave in production.

version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: seanraff89/get-started:part1
    deploy:
      #replicate service 5 times
      replicas: 5
      resources:
        limits:
          #allocate 10% of cpu to a single service
          cpus: "0.1"
          #allocate 50mb of system memory
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      #assign port 80 of VM to 80 of container
      - "80:80"
    networks:
      #Define the webnet network with the default settings (which is a load-balanced overlay network).
      - webnet
    #Define the usage of redis for data persistence
    redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
